import Mathlib
import RHLean.Analysis.MertensStepGrowth

/-!
# Mellin continuation attached to the Mertens summatory function

Under the repository's Mertens energy criterion, the floor-step function has
power growth `O(t^r)` at infinity for every `r > 1/2` and vanishes near zero.
Mathlib's Mellin-transform holomorphy theorem therefore applies directly to

`F(s) = s * mellin mertensStep (-s)`.

This is the Abel/Mellin continuation that will later be identified with the
ordinary Möbius Dirichlet series on `Re(s) > 1`. This file proves holomorphy
only; it makes no zeta nonvanishing claim.
-/

noncomputable section

namespace RHLean.Analysis

open Complex Set

/-- Abel/Mellin continuation generated by the Mertens step function. -/
def mertensMellinContinuation (s : ℂ) : ℂ :=
  s * mellin mertensStep (-s)

/-- The Mertens energy criterion makes the Mellin continuation holomorphic at
every point strictly to the right of the critical line. The auxiliary exponent
`r` is chosen strictly between `1/2` and `re s`; the Mellin strip is then read at
`-s`, with upper boundary `-r` and a harmless lower boundary one unit below
`-re s`. -/
theorem differentiableAt_mertensMellinContinuation
    (hM : MertensEnergyBoundedStatement) {s : ℂ}
    (hs : (1 : ℝ) / 2 < s.re) :
    DifferentiableAt ℂ (mertensMellinContinuation) s := by
  obtain ⟨r, hr, hrs⟩ := exists_between hs
  have htop := mertensStep_isBigO_rpow_atTop hM hr
  have hbot := mertensStep_isBigO_rpow_zero (s.re + 1)
  have hmellin : DifferentiableAt ℂ (mellin mertensStep) (-s) := by
    apply mellin_differentiableAt_of_isBigO_rpow
      (a := -r) (b := -s.re - 1)
      mertensStep_locallyIntegrableOn
    · simpa only [neg_neg] using htop
    · simp only [neg_re]
      linarith
    · convert hbot using 1
      ring_nf
    · simp only [neg_re]
      linarith
  have hcomp :
      DifferentiableAt ℂ (fun z : ℂ => mellin mertensStep (-z)) s := by
    have hneg : DifferentiableAt ℂ (fun z : ℂ => -z) s :=
      differentiableAt_id.neg
    simpa only [Function.comp_apply] using hmellin.comp s hneg
  simpa [mertensMellinContinuation] using differentiableAt_id.mul hcomp

/-- Holomorphy on the open half-plane `Re(s) > 1/2`. -/
theorem differentiableOn_mertensMellinContinuation
    (hM : MertensEnergyBoundedStatement) :
    DifferentiableOn ℂ mertensMellinContinuation
      {s : ℂ | (1 : ℝ) / 2 < s.re} := by
  intro s hs
  exact (differentiableAt_mertensMellinContinuation hM hs).differentiableWithinAt

end RHLean.Analysis
