import Mathlib
import RHLean.Arithmetic.PrimorialWheelCancellation

/-!
# Four-prime wheel cancellation

This file isolates the exact finite self-similarity generated by the first four
primes `2, 3, 5, 7`.  The resulting sign pattern is periodic modulo
`210 = 2 * 3 * 5 * 7`, and its signed mass on every complete `210`-cell is zero.

This is a finite wheel statement.  It does not identify the wheel sign with the
full Mobius function on integers having prime factors above `7`.
-/

noncomputable section

open scoped BigOperators

namespace RHLean.Arithmetic

/-- The primorial of the first four primes. -/
def fourPrimeWheelPeriod : ℕ := 210

/-- Parity sign contributed by divisibility by `2, 3, 5, 7`.

The input is reduced modulo `210`, so periodicity is built into the definition.
Each distinct small-prime divisor flips the sign once. -/
def fourPrimeWheelSign (n : ℕ) : ℤ :=
  let r := n % fourPrimeWheelPeriod
  (if 2 ∣ r then -1 else 1) *
  (if 3 ∣ r then -1 else 1) *
  (if 5 ∣ r then -1 else 1) *
  (if 7 ∣ r then -1 else 1)

/-- The wheel sign is always `+1` or `-1`. -/
theorem fourPrimeWheelSign_eq_one_or_neg_one (n : ℕ) :
    fourPrimeWheelSign n = 1 ∨ fourPrimeWheelSign n = -1 := by
  simp only [fourPrimeWheelSign]
  split_ifs <;> norm_num

/-- Exact `210`-periodicity. -/
@[simp] theorem fourPrimeWheelSign_add_period (n : ℕ) :
    fourPrimeWheelSign (n + fourPrimeWheelPeriod) = fourPrimeWheelSign n := by
  simp [fourPrimeWheelSign, fourPrimeWheelPeriod]

/-- The first complete four-prime wheel has zero signed mass. -/
theorem fourPrimeWheel_completeCell_zero :
    ∑ r ∈ Finset.range fourPrimeWheelPeriod, fourPrimeWheelSign r = 0 := by
  native_decide

/-- Every translated complete wheel cell beginning at a multiple of `210` has
zero signed mass. -/
theorem fourPrimeWheel_translatedCell_zero (q : ℕ) :
    ∑ r ∈ Finset.range fourPrimeWheelPeriod,
      fourPrimeWheelSign (q * fourPrimeWheelPeriod + r) = 0 := by
  have hperiod : ∀ r : ℕ,
      fourPrimeWheelSign (q * fourPrimeWheelPeriod + r) = fourPrimeWheelSign r := by
    intro r
    unfold fourPrimeWheelSign
    simp [fourPrimeWheelPeriod, Nat.add_mod]
  calc
    ∑ r ∈ Finset.range fourPrimeWheelPeriod,
        fourPrimeWheelSign (q * fourPrimeWheelPeriod + r) =
      ∑ r ∈ Finset.range fourPrimeWheelPeriod, fourPrimeWheelSign r := by
        apply Finset.sum_congr rfl
        intro r hr
        exact hperiod r
    _ = 0 := fourPrimeWheel_completeCell_zero

/-- Pairing by a half-period reverses the four-prime wheel sign.

Adding `105` preserves divisibility by `3,5,7` and flips parity, so it flips the
sign.  This is checked on the finite residue system modulo `210`. -/
theorem fourPrimeWheel_halfPeriod_sign_reversal (r : ℕ)
    (hr : r < fourPrimeWheelPeriod) :
    fourPrimeWheelSign (r + 105) = -fourPrimeWheelSign r := by
  have hbound : r < 210 := by
    unfold fourPrimeWheelPeriod at hr
    exact hr
  have hall : ∀ k < 210, fourPrimeWheelSign (k + 105) = -fourPrimeWheelSign k := by
    native_decide
  exact hall r hbound

/-- The concrete `2,3,5,7` wheel satisfies the abstract half-reversal law with
odd-prime cell length `105`. -/
theorem fourPrimeWheel_hasHalfReversal :
    HasWheelHalfReversal 105 fourPrimeWheelSign := by
  intro r hr
  have hrp : r < fourPrimeWheelPeriod := by
    unfold fourPrimeWheelPeriod
    omega
  have h := fourPrimeWheel_halfPeriod_sign_reversal r hrp
  rwa [Nat.add_comm r 105] at h

/-- The concrete complete-cell cancellation is an instance of the general
primorial half-reversal theorem. -/
theorem fourPrimeWheel_completeCell_zero_generalized :
    ∑ r ∈ Finset.range (2 * 105), fourPrimeWheelSign r = 0 :=
  sum_two_mul_cell_eq_zero_of_halfReversal
    105 fourPrimeWheelSign fourPrimeWheel_hasHalfReversal

/-- A partial wheel segment has absolute signed mass at most its length. -/
theorem abs_fourPrimeWheel_partial_sum_le_length (a L : ℕ) :
    |∑ j ∈ Finset.range L, fourPrimeWheelSign (a + j)| ≤ (L : ℤ) := by
  have hpoint : ∀ j ∈ Finset.range L,
      |fourPrimeWheelSign (a + j)| ≤ (1 : ℤ) := by
    intro j hj
    rcases fourPrimeWheelSign_eq_one_or_neg_one (a + j) with h | h <;> simp [h]
  calc
    |∑ j ∈ Finset.range L, fourPrimeWheelSign (a + j)|
        ≤ ∑ j ∈ Finset.range L, |fourPrimeWheelSign (a + j)| :=
          Finset.abs_sum_le_sum_abs _ _
    _ ≤ ∑ _j ∈ Finset.range L, (1 : ℤ) := by
          exact Finset.sum_le_sum hpoint
    _ = (L : ℤ) := by simp

end RHLean.Arithmetic
