import Mathlib
import RHLean.Proof.CanonicalRoughReciprocalCompression
import RHLean.Proof.NearOrthogonality

/-!
# Quantitative Euler contraction and Abel return for canonical rough covariance

`CanonicalRoughReciprocalCompression` puts the native PNT Euler factor
`1 - 1/p` on the exact RH-critical reciprocal covariance carrier, but stops at
exact identities.  This file adds the first genuinely quantitative layer.

There are two pieces.

1. A many-prime signed-defect ledger.  For a chronological descending list of
   fresh-prime steps, a defect created at a smaller prime is transported by all
   already-applied larger-prime Euler factors.  If

   `Delta = max_i p_i * ||D_i||`

   for the *signed aggregate* physical defect layer `D_i`, then the reciprocal
   `1/p_i` suppression and the Euler factors telescope to

   `||ledger|| <= (1 - P) * Delta`,

   where `P = prod_i (1 - 1/p_i)`.  No threshold/top-escape/birth triangle
   split is taken inside `D_i`.

2. A finite Abel return from reciprocal prefixes to the original unweighted
   centered covariance numerator.  The sharp return surface is the complete
   prefix profile

   `n * ||V_R(n)|| + sum_{k<n} ||V_R(k)||`.

   In particular, if every reciprocal prefix through `n` has norm at most `A`,
   then the unweighted numerator is at most `2 * n * A`.

At `n = X_R` these estimates directly bound
`cofactorCard(R) * canonicalRoughCovariance(R)`.

The remaining arithmetic target is therefore explicit: prove a small bound on
the scaled signed defect floor uniformly for the reciprocal prefixes produced by
the descending prime compression.  The algebra here does not replace that hard
estimate by an unsigned support bound.
-/

noncomputable section

open scoped ArithmeticFunction.Moebius BigOperators

namespace RHLean.Proof

open RHLean.Analysis
open CanonicalRoughPrimeAdditionDescent

attribute [local instance] Classical.propDecidable

/-! ## Euler factors and signed physical defect transport -/

/-- Real Euler contraction factor attached to one fresh prime. -/
def canonicalRoughEulerFactor (p : ℕ) : ℝ :=
  1 - 1 / (p : ℝ)

/-- One physical compression step records the prime and the active carrier on
which its signed reciprocal defect mass is evaluated. -/
abbrev CanonicalRoughPhysicalEulerStep := ℕ × Finset ℕ

/-- Product of the Euler contraction factors in a chronological step list. -/
def canonicalRoughEulerProduct : List CanonicalRoughPhysicalEulerStep → ℝ
  | [] => 1
  | step :: steps =>
      canonicalRoughEulerFactor step.1 * canonicalRoughEulerProduct steps

/-- The signed reciprocal defect mass generated by one physical step. -/
def squareRootCanonicalRoughPhysicalStepDefect
    (R : ℕ) (step : CanonicalRoughPhysicalEulerStep) : ℂ :=
  squareRootCanonicalRoughFreshPrimeReciprocalPhysicalDefectMass
    R step.1 step.2

/-- Transported signed defect ledger.  The head step is the larger/earlier
prime: it contracts the entire ledger generated by the later/smaller steps,
exactly as in the two-prime theorem merged in an earlier layer. -/
def squareRootCanonicalRoughTransportedDefectLedger
    (R : ℕ) : List CanonicalRoughPhysicalEulerStep → ℂ
  | [] => 0
  | step :: steps =>
      (canonicalRoughEulerFactor step.1 : ℂ) *
          squareRootCanonicalRoughTransportedDefectLedger R steps +
        squareRootCanonicalRoughPhysicalStepDefect R step

/-- Maximum scaled norm of a *signed aggregate* defect layer.  This retains all
cancellation inside the threshold/top-escape/birth bracket and inside the full
prime layer. -/
def squareRootCanonicalRoughScaledSignedDefectFloor
    (R : ℕ) : List CanonicalRoughPhysicalEulerStep → ℝ
  | [] => 0
  | step :: steps =>
      max ((step.1 : ℝ) * ‖squareRootCanonicalRoughPhysicalStepDefect R step‖)
        (squareRootCanonicalRoughScaledSignedDefectFloor R steps)

/-- Prime Euler factors are nonnegative. -/
theorem canonicalRoughEulerFactor_nonneg
    {p : ℕ} (hp : p.Prime) :
    0 ≤ canonicalRoughEulerFactor p := by
  have hpPos : 0 < (p : ℝ) := by
    exact_mod_cast hp.pos
  have hpOne : (1 : ℝ) ≤ p := by
    exact_mod_cast hp.one_le
  have hdiv : 1 / (p : ℝ) ≤ 1 := by
    apply (div_le_iff₀ hpPos).2
    simpa using hpOne
  unfold canonicalRoughEulerFactor
  linarith

/-- Prime Euler factors do not exceed one. -/
theorem canonicalRoughEulerFactor_le_one
    {p : ℕ} (hp : p.Prime) :
    canonicalRoughEulerFactor p ≤ 1 := by
  have hpPos : 0 < (p : ℝ) := by
    exact_mod_cast hp.pos
  have hdiv : 0 ≤ 1 / (p : ℝ) := (one_div_pos.mpr hpPos).le
  unfold canonicalRoughEulerFactor
  linarith

/-- A product of prime Euler factors is nonnegative. -/
theorem canonicalRoughEulerProduct_nonneg
    (steps : List CanonicalRoughPhysicalEulerStep)
    (hprime : ∀ step ∈ steps, step.1.Prime) :
    0 ≤ canonicalRoughEulerProduct steps := by
  induction steps with
  | nil => simp [canonicalRoughEulerProduct]
  | cons step steps ih =>
      have hp : step.1.Prime := hprime step (by simp)
      have htail : ∀ s ∈ steps, s.1.Prime := by
        intro s hs
        exact hprime s (by simp [hs])
      simp only [canonicalRoughEulerProduct]
      exact mul_nonneg (canonicalRoughEulerFactor_nonneg hp) (ih htail)

/-- A product of prime Euler factors is at most one. -/
theorem canonicalRoughEulerProduct_le_one
    (steps : List CanonicalRoughPhysicalEulerStep)
    (hprime : ∀ step ∈ steps, step.1.Prime) :
    canonicalRoughEulerProduct steps ≤ 1 := by
  induction steps with
  | nil => simp [canonicalRoughEulerProduct]
  | cons step steps ih =>
      have hp : step.1.Prime := hprime step (by simp)
      have htail : ∀ s ∈ steps, s.1.Prime := by
        intro s hs
        exact hprime s (by simp [hs])
      have ha0 := canonicalRoughEulerFactor_nonneg hp
      have ha1 := canonicalRoughEulerFactor_le_one hp
      have hP0 := canonicalRoughEulerProduct_nonneg steps htail
      have hP1 := ih htail
      simp only [canonicalRoughEulerProduct]
      calc
        canonicalRoughEulerFactor step.1 * canonicalRoughEulerProduct steps ≤
            1 * canonicalRoughEulerProduct steps :=
          mul_le_mul_of_nonneg_right ha1 hP0
        _ ≤ 1 := by simpa using hP1

/-- The scaled signed defect floor is nonnegative. -/
theorem squareRootCanonicalRoughScaledSignedDefectFloor_nonneg
    (R : ℕ) (steps : List CanonicalRoughPhysicalEulerStep) :
    0 ≤ squareRootCanonicalRoughScaledSignedDefectFloor R steps := by
  induction steps with
  | nil => simp [squareRootCanonicalRoughScaledSignedDefectFloor]
  | cons step steps ih =>
      simp only [squareRootCanonicalRoughScaledSignedDefectFloor]
      exact le_max_of_le_right ih

/-- Every individual signed defect layer is bounded by the global scaled floor
with its native reciprocal `1/p` factor exposed. -/
theorem squareRootCanonicalRoughPhysicalStepDefect_norm_le_floor_div_prime
    (R : ℕ) (steps : List CanonicalRoughPhysicalEulerStep)
    {step : CanonicalRoughPhysicalEulerStep}
    (hstep : step ∈ steps) (hp : step.1.Prime) :
    ‖squareRootCanonicalRoughPhysicalStepDefect R step‖ ≤
      squareRootCanonicalRoughScaledSignedDefectFloor R steps / (step.1 : ℝ) := by
  have hscaled :
      (step.1 : ℝ) * ‖squareRootCanonicalRoughPhysicalStepDefect R step‖ ≤
        squareRootCanonicalRoughScaledSignedDefectFloor R steps := by
    induction steps with
    | nil => simp at hstep
    | cons head tail ih =>
        simp only [List.mem_cons] at hstep
        simp only [squareRootCanonicalRoughScaledSignedDefectFloor]
        rcases hstep with rfl | htail
        · exact le_max_left _ _
        · exact le_trans (ih htail) (le_max_right _ _)
  have hpPos : 0 < (step.1 : ℝ) := by
    exact_mod_cast hp.pos
  apply (le_div_iff₀ hpPos).2
  simpa [mul_comm] using hscaled

/-- **Many-prime signed defect ledger contraction.**

For a list of genuine prime steps, the transported signed ledger is bounded by
`(1 - P) * Delta`, where `P` is the Euler product and `Delta` is the maximum
scaled signed layer.  The proof is the elementary telescope

`a * (1 - Ptail) * Delta + Delta/p = (1 - a*Ptail) * Delta`

with `a = 1 - 1/p`. -/
theorem squareRootCanonicalRoughTransportedDefectLedger_norm_le
    (R : ℕ) (steps : List CanonicalRoughPhysicalEulerStep)
    (hprime : ∀ step ∈ steps, step.1.Prime) :
    ‖squareRootCanonicalRoughTransportedDefectLedger R steps‖ ≤
      (1 - canonicalRoughEulerProduct steps) *
        squareRootCanonicalRoughScaledSignedDefectFloor R steps := by
  induction steps with
  | nil => simp [squareRootCanonicalRoughTransportedDefectLedger,
      canonicalRoughEulerProduct,
      squareRootCanonicalRoughScaledSignedDefectFloor]
  | cons step steps ih =>
      have hp : step.1.Prime := hprime step (by simp)
      have htailPrime : ∀ s ∈ steps, s.1.Prime := by
        intro s hs
        exact hprime s (by simp [hs])
      let Δ := squareRootCanonicalRoughScaledSignedDefectFloor R (step :: steps)
      let P := canonicalRoughEulerProduct steps
      let a := canonicalRoughEulerFactor step.1
      have hΔ0 : 0 ≤ Δ := by
        dsimp [Δ]
        exact squareRootCanonicalRoughScaledSignedDefectFloor_nonneg R (step :: steps)
      have ha0 : 0 ≤ a := by
        dsimp [a]
        exact canonicalRoughEulerFactor_nonneg hp
      have htailFloor :
          squareRootCanonicalRoughScaledSignedDefectFloor R steps ≤ Δ := by
        dsimp [Δ]
        simp only [squareRootCanonicalRoughScaledSignedDefectFloor]
        exact le_max_right _ _
      have hledgerTail :
          ‖squareRootCanonicalRoughTransportedDefectLedger R steps‖ ≤
            (1 - P) * Δ := by
        have hih := ih htailPrime
        dsimp [P]
        exact hih.trans (mul_le_mul_of_nonneg_left htailFloor
          (by
            have hP1 := canonicalRoughEulerProduct_le_one steps htailPrime
            linarith))
      have hdefect :
          ‖squareRootCanonicalRoughPhysicalStepDefect R step‖ ≤
            Δ / (step.1 : ℝ) := by
        dsimp [Δ]
        exact squareRootCanonicalRoughPhysicalStepDefect_norm_le_floor_div_prime
          R (step :: steps) (by simp) hp
      have hmul :
          ‖(a : ℂ) * squareRootCanonicalRoughTransportedDefectLedger R steps‖ =
            a * ‖squareRootCanonicalRoughTransportedDefectLedger R steps‖ := by
        rw [norm_mul, Complex.norm_real, Real.norm_eq_abs, abs_of_nonneg ha0]
      simp only [squareRootCanonicalRoughTransportedDefectLedger]
      calc
        ‖(a : ℂ) * squareRootCanonicalRoughTransportedDefectLedger R steps +
            squareRootCanonicalRoughPhysicalStepDefect R step‖ ≤
          ‖(a : ℂ) * squareRootCanonicalRoughTransportedDefectLedger R steps‖ +
            ‖squareRootCanonicalRoughPhysicalStepDefect R step‖ :=
          norm_add_le _ _
        _ = a * ‖squareRootCanonicalRoughTransportedDefectLedger R steps‖ +
            ‖squareRootCanonicalRoughPhysicalStepDefect R step‖ := by rw [hmul]
        _ ≤ a * ((1 - P) * Δ) + Δ / (step.1 : ℝ) :=
          add_le_add (mul_le_mul_of_nonneg_left hledgerTail ha0) hdefect
        _ = (1 - a * P) * Δ := by
          dsimp [a, canonicalRoughEulerFactor]
          ring
        _ = (1 - canonicalRoughEulerProduct (step :: steps)) *
            squareRootCanonicalRoughScaledSignedDefectFloor R (step :: steps) := by
          simp [canonicalRoughEulerProduct, a, P, Δ]

/-- The full compressed scalar profile contracts toward the signed defect floor.
This is the direct covariance analogue of the native PNT Euler contraction: the
Euler product multiplies the initial mode and the complementary mass is charged
only to the scaled signed defect floor. -/
theorem squareRootCanonicalRoughCompressedProfile_norm_le
    (R : ℕ) (steps : List CanonicalRoughPhysicalEulerStep) (z : ℂ)
    (hprime : ∀ step ∈ steps, step.1.Prime) :
    ‖(canonicalRoughEulerProduct steps : ℂ) * z +
        squareRootCanonicalRoughTransportedDefectLedger R steps‖ ≤
      canonicalRoughEulerProduct steps * ‖z‖ +
        (1 - canonicalRoughEulerProduct steps) *
          squareRootCanonicalRoughScaledSignedDefectFloor R steps := by
  have hP0 := canonicalRoughEulerProduct_nonneg steps hprime
  have hledger := squareRootCanonicalRoughTransportedDefectLedger_norm_le R steps hprime
  calc
    ‖(canonicalRoughEulerProduct steps : ℂ) * z +
        squareRootCanonicalRoughTransportedDefectLedger R steps‖ ≤
      ‖(canonicalRoughEulerProduct steps : ℂ) * z‖ +
        ‖squareRootCanonicalRoughTransportedDefectLedger R steps‖ :=
      norm_add_le _ _
    _ = canonicalRoughEulerProduct steps * ‖z‖ +
        ‖squareRootCanonicalRoughTransportedDefectLedger R steps‖ := by
      rw [norm_mul, Complex.norm_real, Real.norm_eq_abs, abs_of_nonneg hP0]
    _ ≤ canonicalRoughEulerProduct steps * ‖z‖ +
        (1 - canonicalRoughEulerProduct steps) *
          squareRootCanonicalRoughScaledSignedDefectFloor R steps :=
      add_le_add_left hledger _

/-! ## Finite Abel return to the unweighted covariance numerator -/

/-- Reciprocal prefix of the exact response-centered covariance carrier.  The
zero term is harmless because the reciprocal summand is multiplied by the
index in the Abel identity. -/
def squareRootCanonicalRoughReciprocalPrefix (R n : ℕ) : ℂ :=
  inclusivePrefix
    (fun c => squareRootCanonicalRoughResponseCenteredReciprocalSummand R c) n

/-- Recover one positive unweighted centered summand from the reciprocal one. -/
theorem natCast_mul_squareRootCanonicalRoughResponseCenteredReciprocalSummand
    (R : ℕ) {c : ℕ} (hc : 0 < c) :
    (c : ℂ) * squareRootCanonicalRoughResponseCenteredReciprocalSummand R c =
      squareRootCanonicalRoughResponseCenteredSummand R c := by
  unfold squareRootCanonicalRoughResponseCenteredReciprocalSummand
  have hc0 : (c : ℂ) ≠ 0 := by
    exact_mod_cast (Nat.ne_of_gt hc)
  field_simp [hc0]

/-- Exact finite Abel reconstruction of the unweighted centered covariance
numerator from reciprocal prefixes. -/
theorem sum_squareRootCanonicalRoughResponseCentered_eq_abel_reciprocalPrefix
    (R n : ℕ) :
    (∑ c ∈ Finset.Icc 1 n,
        squareRootCanonicalRoughResponseCenteredSummand R c) =
      (n : ℂ) * squareRootCanonicalRoughReciprocalPrefix R n -
        ∑ k ∈ Finset.range n,
          squareRootCanonicalRoughReciprocalPrefix R k := by
  let v : ℕ → ℂ :=
    fun c => squareRootCanonicalRoughResponseCenteredReciprocalSummand R c
  have habel := finite_abel_identity v (fun k : ℕ => (k : ℂ)) n
  have hleft :
      (∑ c ∈ Finset.Icc 1 n,
          squareRootCanonicalRoughResponseCenteredSummand R c) =
        ∑ c ∈ Finset.range (n + 1), v c * (c : ℂ) := by
    have hset : Finset.Icc 1 n = Finset.range (n + 1) \ {0} := by
      ext c
      simp
      omega
    rw [hset]
    have hsub : ({0} : Finset ℕ) ⊆ Finset.range (n + 1) := by
      intro c hc
      simp at hc
      subst c
      simp
    have hsplit :=
      Finset.sum_sdiff hsub (f := fun c => v c * (c : ℂ))
    have hweighted :
        (∑ c ∈ Finset.range (n + 1) \ {0}, v c * (c : ℂ)) =
          ∑ c ∈ Finset.range (n + 1) \ {0},
            squareRootCanonicalRoughResponseCenteredSummand R c := by
      apply Finset.sum_congr rfl
      intro c hc
      have hc0 : c ≠ 0 := by
        have hcnot : c ∉ ({0} : Finset ℕ) := (Finset.mem_sdiff.mp hc).2
        simpa using hcnot
      rw [← natCast_mul_squareRootCanonicalRoughResponseCenteredReciprocalSummand
        R (Nat.pos_of_ne_zero hc0)]
      ring
    rw [hweighted] at hsplit
    simpa [v] using hsplit
  rw [hleft]
  rw [habel]
  unfold squareRootCanonicalRoughReciprocalPrefix
  simp only [inclusivePrefix]
  have hdiff : ∀ k : ℕ, (k : ℂ) - ((k + 1 : ℕ) : ℂ) = -1 := by
    intro k
    push_cast
    ring
  simp_rw [hdiff, mul_neg_one]
  rw [Finset.sum_neg_distrib]
  ring

/-- Exact Abel profile budget.  This is the sharp return surface for a later
scale-dependent contraction theorem; no uniform prefix envelope is imposed. -/
def squareRootCanonicalRoughReciprocalAbelBudget (R n : ℕ) : ℝ :=
  (n : ℝ) * ‖squareRootCanonicalRoughReciprocalPrefix R n‖ +
    ∑ k ∈ Finset.range n,
      ‖squareRootCanonicalRoughReciprocalPrefix R k‖

/-- The original unweighted centered numerator is bounded by the complete
reciprocal-prefix Abel profile. -/
theorem norm_sum_squareRootCanonicalRoughResponseCentered_le_abelBudget
    (R n : ℕ) :
    ‖∑ c ∈ Finset.Icc 1 n,
        squareRootCanonicalRoughResponseCenteredSummand R c‖ ≤
      squareRootCanonicalRoughReciprocalAbelBudget R n := by
  rw [sum_squareRootCanonicalRoughResponseCentered_eq_abel_reciprocalPrefix]
  unfold squareRootCanonicalRoughReciprocalAbelBudget
  calc
    ‖(n : ℂ) * squareRootCanonicalRoughReciprocalPrefix R n -
        ∑ k ∈ Finset.range n,
          squareRootCanonicalRoughReciprocalPrefix R k‖ ≤
      ‖(n : ℂ) * squareRootCanonicalRoughReciprocalPrefix R n‖ +
        ‖∑ k ∈ Finset.range n,
          squareRootCanonicalRoughReciprocalPrefix R k‖ :=
      norm_sub_le _ _
    _ ≤ (n : ℝ) * ‖squareRootCanonicalRoughReciprocalPrefix R n‖ +
        ∑ k ∈ Finset.range n,
          ‖squareRootCanonicalRoughReciprocalPrefix R k‖ := by
      apply add_le_add
      · rw [norm_mul]
        simp
      · exact norm_sum_le _ _

/-- A pointwise envelope for the reciprocal-prefix profile returns directly
through Abel summation, without replacing it by its worst prefix. -/
theorem norm_sum_squareRootCanonicalRoughResponseCentered_le_profile
    (R n : ℕ) (A : ℕ → ℝ)
    (hprefix : ∀ k ≤ n,
      ‖squareRootCanonicalRoughReciprocalPrefix R k‖ ≤ A k) :
    ‖∑ c ∈ Finset.Icc 1 n,
        squareRootCanonicalRoughResponseCenteredSummand R c‖ ≤
      (n : ℝ) * A n + ∑ k ∈ Finset.range n, A k := by
  exact (norm_sum_squareRootCanonicalRoughResponseCentered_le_abelBudget R n).trans <| by
    unfold squareRootCanonicalRoughReciprocalAbelBudget
    apply add_le_add
    · exact mul_le_mul_of_nonneg_left (hprefix n le_rfl) (by positivity)
    · apply Finset.sum_le_sum
      intro k hk
      exact hprefix k (Nat.le_of_lt (Finset.mem_range.mp hk))

/-- Uniform reciprocal-prefix control is the coarse corollary of the sharper
profile return and costs only the finite Abel factor `2n`. -/
theorem norm_sum_squareRootCanonicalRoughResponseCentered_le_two_mul_of_prefix_bound
    (R n : ℕ) (A : ℝ)
    (hprefix : ∀ k ≤ n,
      ‖squareRootCanonicalRoughReciprocalPrefix R k‖ ≤ A) :
    ‖∑ c ∈ Finset.Icc 1 n,
        squareRootCanonicalRoughResponseCenteredSummand R c‖ ≤
      2 * (n : ℝ) * A := by
  rw [sum_squareRootCanonicalRoughResponseCentered_eq_abel_reciprocalPrefix]
  have hend :
      ‖(n : ℂ) * squareRootCanonicalRoughReciprocalPrefix R n‖ ≤
        (n : ℝ) * A := by
    rw [norm_mul]
    have hnNorm : ‖(n : ℂ)‖ = (n : ℝ) := by simp
    rw [hnNorm]
    exact mul_le_mul_of_nonneg_left (hprefix n le_rfl) (by positivity)
  have hsum :
      ‖∑ k ∈ Finset.range n,
          squareRootCanonicalRoughReciprocalPrefix R k‖ ≤
        (n : ℝ) * A := by
    calc
      ‖∑ k ∈ Finset.range n,
          squareRootCanonicalRoughReciprocalPrefix R k‖ ≤
        ∑ k ∈ Finset.range n,
          ‖squareRootCanonicalRoughReciprocalPrefix R k‖ :=
        norm_sum_le _ _
      _ ≤ ∑ _k ∈ Finset.range n, A := by
        apply Finset.sum_le_sum
        intro k hk
        exact hprefix k (by
          have hklt := Finset.mem_range.mp hk
          omega)
      _ = (n : ℝ) * A := by simp
  calc
    ‖(n : ℂ) * squareRootCanonicalRoughReciprocalPrefix R n -
        ∑ k ∈ Finset.range n,
          squareRootCanonicalRoughReciprocalPrefix R k‖ ≤
      ‖(n : ℂ) * squareRootCanonicalRoughReciprocalPrefix R n‖ +
        ‖∑ k ∈ Finset.range n,
          squareRootCanonicalRoughReciprocalPrefix R k‖ :=
      norm_sub_le _ _
    _ ≤ (n : ℝ) * A + (n : ℝ) * A := add_le_add hend hsum
    _ = 2 * (n : ℝ) * A := by ring

/-- **Sharp finite Abel return on the exact RH-critical covariance carrier.**
At the square endpoint the covariance numerator is controlled by the complete
reciprocal-prefix profile, with no extra arithmetic hypothesis. -/
theorem squareRootCanonicalRoughCovarianceNumerator_norm_le_abelBudget
    (R : ℕ) (hR : 2 ≤ R) :
    ‖(squareRootCanonicalRoughCofactorCard R : ℂ) *
        squareRootCanonicalRoughCovariance R‖ ≤
      squareRootCanonicalRoughReciprocalAbelBudget R (squareRootEndpoint R) := by
  rw [squareRootCanonicalRoughCofactorCard_mul_covariance_eq_sum_responseCentered
    R hR]
  exact
    norm_sum_squareRootCanonicalRoughResponseCentered_le_abelBudget
      R (squareRootEndpoint R)

/-- Uniform-prefix endpoint corollary of the sharp Abel return. -/
theorem squareRootCanonicalRoughCovarianceNumerator_norm_le_two_endpoint_mul
    (R : ℕ) (hR : 2 ≤ R) (A : ℝ)
    (hprefix : ∀ k ≤ squareRootEndpoint R,
      ‖squareRootCanonicalRoughReciprocalPrefix R k‖ ≤ A) :
    ‖(squareRootCanonicalRoughCofactorCard R : ℂ) *
        squareRootCanonicalRoughCovariance R‖ ≤
      2 * (squareRootEndpoint R : ℝ) * A := by
  rw [squareRootCanonicalRoughCofactorCard_mul_covariance_eq_sum_responseCentered
    R hR]
  exact
    norm_sum_squareRootCanonicalRoughResponseCentered_le_two_mul_of_prefix_bound
      R (squareRootEndpoint R) A hprefix

end RHLean.Proof
