import Mathlib
import RHLean.Proof.CanonicalRoughDefectLedgerBound

/-!
# Many-prime contraction of the compressed reciprocal covariance profile

`CanonicalRoughReciprocalCompression` compresses one fresh prime, and then a
second one on the four corners of a Boolean square.  This file iterates the
same reciprocal Euler law over an arbitrary finite ascending chain of fresh
primes and shows that the compressed profile genuinely contracts while the
defect terms stay under explicit control.

The carrier of the iteration is the Boolean cube generated by a strictly
increasing list `L = [q_1 < q_2 < ... < q_k]` of primes above the canonical
largest prime factor of `c`:

```text
cube R L c = sum over sublists S of L of v_R(c * prod S).
```

Peeling the smallest prime `q_1` compresses the two halves of the cube onto each
other, so the whole cube collapses onto the single base coordinate with the
complete Euler product attached:

```text
cube R L c = prod_{q in L} (1 - 1/q) * v_R(c) + cubeDefect R L c.
```

That identity is exact.  The quantitative half is the pair of estimates

```text
‖cubeDefect R L c‖  <=  cubeLedgerBudget R L c,
prod_{q in L} (1 - 1/q)  <=  exp(-sum_{q in L} 1/q),
```

the first because every Euler factor carried along a compression has norm at
most one, so the recursion never amplifies a defect, and the second by the
elementary inequality `1 - x <= exp(-x)`.  Combining them gives the headline
contraction: the compressed reciprocal profile decays like the Mertens
exponential of the chain, up to an explicitly summed arithmetic ledger built
from the reciprocal windows of `CanonicalRoughDefectLedgerBound`.

Nothing here is asymptotic, and the chain `L` is arbitrary: no prime counting
or analytic input is used at any point.
-/

noncomputable section

open scoped ArithmeticFunction.Moebius BigOperators

namespace RHLean.Proof

open RHLean.Analysis
open CanonicalRoughFreshPrimeDifference
open CanonicalRoughPrimeAdditionDescent

attribute [local instance] Classical.propDecidable

/-! ## Ascending fresh prime chains -/

/-- A strictly increasing list of primes, every entry above the bound `b`.  With
`b = P^+(c)` this is exactly the legality condition for compressing the whole
list onto `c`, because adjoining a fresh prime moves the canonical largest prime
factor to that prime, so the next entry must clear the previous one. -/
def IsCanonicalFreshPrimeChain : ℕ → List ℕ → Prop
  | _b, [] => True
  | b, q :: L => q.Prime ∧ b < q ∧ IsCanonicalFreshPrimeChain q L

theorem isCanonicalFreshPrimeChain_nil (b : ℕ) :
    IsCanonicalFreshPrimeChain b [] := by
  trivial

theorem isCanonicalFreshPrimeChain_cons {b q : ℕ} {L : List ℕ} :
    IsCanonicalFreshPrimeChain b (q :: L) ↔
      q.Prime ∧ b < q ∧ IsCanonicalFreshPrimeChain q L := by
  exact Iff.rfl

/-- Lowering the bound keeps a fresh prime chain legal. -/
theorem isCanonicalFreshPrimeChain_of_le {b b' : ℕ} {L : List ℕ}
    (hb : b' ≤ b) (h : IsCanonicalFreshPrimeChain b L) :
    IsCanonicalFreshPrimeChain b' L := by
  cases L with
  | nil => exact isCanonicalFreshPrimeChain_nil b'
  | cons q L =>
      rcases isCanonicalFreshPrimeChain_cons.1 h with ⟨hq, hbq, hrest⟩
      exact isCanonicalFreshPrimeChain_cons.2 ⟨hq, lt_of_le_of_lt hb hbq, hrest⟩

/-- Every entry of a fresh prime chain is at least two. -/
theorem two_le_of_isCanonicalFreshPrimeChain :
    ∀ (L : List ℕ) (b : ℕ), IsCanonicalFreshPrimeChain b L → ∀ q ∈ L, 2 ≤ q := by
  intro L
  induction L with
  | nil =>
      intro _b _h q hq
      simp at hq
  | cons r L ih =>
      intro _b h q hq
      rcases isCanonicalFreshPrimeChain_cons.1 h with ⟨hr, _hbr, hrest⟩
      rcases List.mem_cons.1 hq with rfl | hq'
      · exact hr.two_le
      · exact ih r hrest q hq'

/-! ## Euler factors of a chain -/

/-- Complex Euler factor of a finite prime list. -/
def squareRootCanonicalRoughCubeEulerFactor (L : List ℕ) : ℂ :=
  (L.map fun r => 1 - 1 / (r : ℂ)).prod

@[simp] theorem squareRootCanonicalRoughCubeEulerFactor_nil :
    squareRootCanonicalRoughCubeEulerFactor [] = 1 := by
  simp [squareRootCanonicalRoughCubeEulerFactor]

@[simp] theorem squareRootCanonicalRoughCubeEulerFactor_cons (q : ℕ) (L : List ℕ) :
    squareRootCanonicalRoughCubeEulerFactor (q :: L) =
      (1 - 1 / (q : ℂ)) * squareRootCanonicalRoughCubeEulerFactor L := by
  simp [squareRootCanonicalRoughCubeEulerFactor]

/-- Real Euler factor of the same list. -/
def squareRootCanonicalRoughCubeEulerFactorReal (L : List ℕ) : ℝ :=
  (L.map fun r => 1 - 1 / (r : ℝ)).prod

@[simp] theorem squareRootCanonicalRoughCubeEulerFactorReal_nil :
    squareRootCanonicalRoughCubeEulerFactorReal [] = 1 := by
  simp [squareRootCanonicalRoughCubeEulerFactorReal]

@[simp] theorem squareRootCanonicalRoughCubeEulerFactorReal_cons (q : ℕ) (L : List ℕ) :
    squareRootCanonicalRoughCubeEulerFactorReal (q :: L) =
      (1 - 1 / (q : ℝ)) * squareRootCanonicalRoughCubeEulerFactorReal L := by
  simp [squareRootCanonicalRoughCubeEulerFactorReal]

/-- Reciprocal prime sum of the chain: the Mertens exponent of the contraction. -/
def squareRootCanonicalRoughCubeReciprocalPrimeSum (L : List ℕ) : ℝ :=
  (L.map fun r => 1 / (r : ℝ)).sum

@[simp] theorem squareRootCanonicalRoughCubeReciprocalPrimeSum_nil :
    squareRootCanonicalRoughCubeReciprocalPrimeSum [] = 0 := by
  simp [squareRootCanonicalRoughCubeReciprocalPrimeSum]

@[simp] theorem squareRootCanonicalRoughCubeReciprocalPrimeSum_cons (q : ℕ) (L : List ℕ) :
    squareRootCanonicalRoughCubeReciprocalPrimeSum (q :: L) =
      1 / (q : ℝ) + squareRootCanonicalRoughCubeReciprocalPrimeSum L := by
  simp [squareRootCanonicalRoughCubeReciprocalPrimeSum]

/-- One Euler factor is a genuine contraction: its norm is exactly `1 - 1/q`. -/
theorem norm_one_sub_one_div_natCast {q : ℕ} (hq : 2 ≤ q) :
    ‖(1 : ℂ) - 1 / (q : ℂ)‖ = 1 - 1 / (q : ℝ) := by
  have hq1 : 1 ≤ q := by omega
  have hqR : (0 : ℝ) < (q : ℝ) := by
    have h : 0 < q := by omega
    exact_mod_cast h
  have hqRne : (q : ℝ) ≠ 0 := ne_of_gt hqR
  have hq0 : (q : ℂ) ≠ 0 := by
    have h : q ≠ 0 := by omega
    exact_mod_cast h
  have hcastC : ((q - 1 : ℕ) : ℂ) = (q : ℂ) - 1 := by
    rw [Nat.cast_sub hq1, Nat.cast_one]
  have hcastR : ((q - 1 : ℕ) : ℝ) = (q : ℝ) - 1 := by
    rw [Nat.cast_sub hq1, Nat.cast_one]
  have hrewrite : (1 : ℂ) - 1 / (q : ℂ) = ((q - 1 : ℕ) : ℂ) / (q : ℂ) := by
    rw [hcastC, sub_div, div_self hq0]
  rw [hrewrite, norm_div]
  simp only [Complex.norm_natCast]
  rw [hcastR, sub_div, div_self hqRne]

/-- Every Euler factor is a weak contraction. -/
theorem norm_one_sub_one_div_natCast_le_one {q : ℕ} (hq : 2 ≤ q) :
    ‖(1 : ℂ) - 1 / (q : ℂ)‖ ≤ 1 := by
  rw [norm_one_sub_one_div_natCast hq]
  have hqR : (0 : ℝ) < (q : ℝ) := by
    have h : 0 < q := by omega
    exact_mod_cast h
  have hpos : (0 : ℝ) < 1 / (q : ℝ) := div_pos one_pos hqR
  linarith

/-- The Euler factor of a whole chain never amplifies. -/
theorem norm_squareRootCanonicalRoughCubeEulerFactor_le_one (L : List ℕ)
    (hL : ∀ q ∈ L, 2 ≤ q) :
    ‖squareRootCanonicalRoughCubeEulerFactor L‖ ≤ 1 := by
  induction L with
  | nil => simp
  | cons q L ih =>
      have hq : 2 ≤ q := hL q (by simp)
      have hrest : ∀ r ∈ L, 2 ≤ r := fun r hr => hL r (by simp [hr])
      rw [squareRootCanonicalRoughCubeEulerFactor_cons, norm_mul]
      calc
        ‖(1 : ℂ) - 1 / (q : ℂ)‖ * ‖squareRootCanonicalRoughCubeEulerFactor L‖ ≤ 1 * 1 :=
          mul_le_mul (norm_one_sub_one_div_natCast_le_one hq) (ih hrest)
            (norm_nonneg _) (by norm_num)
        _ = 1 := by norm_num

/-- The complex Euler factor has exactly the real Euler product as its norm. -/
theorem norm_squareRootCanonicalRoughCubeEulerFactor_eq_real (L : List ℕ)
    (hL : ∀ q ∈ L, 2 ≤ q) :
    ‖squareRootCanonicalRoughCubeEulerFactor L‖ =
      squareRootCanonicalRoughCubeEulerFactorReal L := by
  induction L with
  | nil => simp
  | cons q L ih =>
      have hq : 2 ≤ q := hL q (by simp)
      have hrest : ∀ r ∈ L, 2 ≤ r := fun r hr => hL r (by simp [hr])
      rw [squareRootCanonicalRoughCubeEulerFactor_cons,
        squareRootCanonicalRoughCubeEulerFactorReal_cons, norm_mul, ih hrest,
        norm_one_sub_one_div_natCast hq]

/-- The real Euler product of a prime chain is nonnegative. -/
theorem squareRootCanonicalRoughCubeEulerFactorReal_nonneg (L : List ℕ)
    (hL : ∀ q ∈ L, 2 ≤ q) :
    0 ≤ squareRootCanonicalRoughCubeEulerFactorReal L := by
  induction L with
  | nil => simp
  | cons q L ih =>
      have hq : 2 ≤ q := hL q (by simp)
      have hrest : ∀ r ∈ L, 2 ≤ r := fun r hr => hL r (by simp [hr])
      have hqR : (0 : ℝ) < (q : ℝ) := by
        have h : 0 < q := by omega
        exact_mod_cast h
      have hqR1 : (1 : ℝ) ≤ (q : ℝ) := by
        have h : 1 ≤ q := by omega
        exact_mod_cast h
      have hfac : (0 : ℝ) ≤ 1 - 1 / (q : ℝ) := by
        rw [sub_nonneg, div_le_one hqR]
        exact hqR1
      rw [squareRootCanonicalRoughCubeEulerFactorReal_cons]
      exact mul_nonneg hfac (ih hrest)

/-- **Mertens decay of the chain Euler product.**  The compressed profile really
contracts: the accumulated Euler factor is at most the exponential of minus the
reciprocal prime sum of the chain. -/
theorem squareRootCanonicalRoughCubeEulerFactorReal_le_exp_neg (L : List ℕ)
    (hL : ∀ q ∈ L, 2 ≤ q) :
    squareRootCanonicalRoughCubeEulerFactorReal L ≤
      Real.exp (-squareRootCanonicalRoughCubeReciprocalPrimeSum L) := by
  induction L with
  | nil => simp
  | cons q L ih =>
      have hrest : ∀ r ∈ L, 2 ≤ r := fun r hr => hL r (by simp [hr])
      have hfac : 1 - 1 / (q : ℝ) ≤ Real.exp (-(1 / (q : ℝ))) := by
        have h := Real.add_one_le_exp (-(1 / (q : ℝ)))
        linarith
      have harg : -(1 / (q : ℝ) + squareRootCanonicalRoughCubeReciprocalPrimeSum L) =
          -(1 / (q : ℝ)) + -squareRootCanonicalRoughCubeReciprocalPrimeSum L := by ring
      rw [squareRootCanonicalRoughCubeEulerFactorReal_cons,
        squareRootCanonicalRoughCubeReciprocalPrimeSum_cons, harg, Real.exp_add]
      exact mul_le_mul hfac (ih hrest)
        (squareRootCanonicalRoughCubeEulerFactorReal_nonneg L hrest)
        (le_of_lt (Real.exp_pos _))

/-! ## The Boolean cube of a fresh prime chain -/

/-- Reciprocal covariance potential of the Boolean cube generated by a chain of
fresh primes.  Splitting on whether the smallest prime is used gives the two
recursive halves. -/
def squareRootCanonicalRoughCubeReciprocalPotential (R : ℕ) : List ℕ → ℕ → ℂ
  | [], c => squareRootCanonicalRoughResponseCenteredReciprocalSummand R c
  | q :: L, c =>
      squareRootCanonicalRoughCubeReciprocalPotential R L c +
        squareRootCanonicalRoughCubeReciprocalPotential R L (c * q)

/-- Accumulated signed reciprocal physical defect of the same compression.  Each
compression step carries its own defect through every later Euler factor. -/
def squareRootCanonicalRoughCubeReciprocalDefect (R : ℕ) : List ℕ → ℕ → ℂ
  | [], _c => 0
  | q :: L, c =>
      squareRootCanonicalRoughCubeEulerFactor L *
          squareRootCanonicalRoughFreshPrimeReciprocalPhysicalDefect R c q +
        squareRootCanonicalRoughCubeReciprocalDefect R L c +
        squareRootCanonicalRoughCubeReciprocalDefect R L (c * q)

/-- Norm budget of the accumulated defect. -/
def squareRootCanonicalRoughCubeReciprocalDefectBudget (R : ℕ) : List ℕ → ℕ → ℝ
  | [], _c => 0
  | q :: L, c =>
      ‖squareRootCanonicalRoughFreshPrimeReciprocalPhysicalDefect R c q‖ +
        squareRootCanonicalRoughCubeReciprocalDefectBudget R L c +
        squareRootCanonicalRoughCubeReciprocalDefectBudget R L (c * q)

/-- Fully explicit arithmetic budget of the accumulated defect, assembled from
the reciprocal windows of the signed defect ledger. -/
def squareRootCanonicalRoughCubeReciprocalLedgerBudget (R : ℕ) : List ℕ → ℕ → ℝ
  | [], _c => 0
  | q :: L, c =>
      (squareRootCanonicalRoughFreshPrimeLedgerWindow R c q : ℝ) / ((c * q : ℕ) : ℝ) +
        squareRootCanonicalRoughCubeReciprocalLedgerBudget R L c +
        squareRootCanonicalRoughCubeReciprocalLedgerBudget R L (c * q)

/-- **Many-prime reciprocal Euler contraction (exact form).**  Iterating the
one-prime Euler law over an ascending chain of fresh primes collapses the whole
Boolean cube onto its base coordinate with the complete Euler product attached.
The only remainder is the accumulated signed reciprocal physical defect. -/
theorem squareRootCanonicalRoughCubeReciprocalPotential_eq_eulerFactor_mul_add_defect
    (R : ℕ) (hR : 2 ≤ R) (L : List ℕ) :
    ∀ c : ℕ, 0 < c →
      IsCanonicalFreshPrimeChain (canonicalLargestPrimeFactor c) L →
      squareRootCanonicalRoughCubeReciprocalPotential R L c =
        squareRootCanonicalRoughCubeEulerFactor L *
            squareRootCanonicalRoughResponseCenteredReciprocalSummand R c +
          squareRootCanonicalRoughCubeReciprocalDefect R L c := by
  induction L with
  | nil =>
      intro c _hc _hchain
      simp [squareRootCanonicalRoughCubeReciprocalPotential,
        squareRootCanonicalRoughCubeReciprocalDefect]
  | cons q L ih =>
      intro c hc hchain
      rcases isCanonicalFreshPrimeChain_cons.1 hchain with ⟨hq, hfresh, hrest⟩
      have hcq : 0 < c * q := Nat.mul_pos hc hq.pos
      have hlpf : canonicalLargestPrimeFactor (c * q) = q :=
        canonicalLargestPrimeFactor_mul_prime_eq_of_rough hc hq hfresh
      have hchainBase : IsCanonicalFreshPrimeChain (canonicalLargestPrimeFactor c) L :=
        isCanonicalFreshPrimeChain_of_le (le_of_lt hfresh) hrest
      have hchainChild :
          IsCanonicalFreshPrimeChain (canonicalLargestPrimeFactor (c * q)) L := by
        rw [hlpf]
        exact hrest
      have hbase := ih c hc hchainBase
      have hchild := ih (c * q) hcq hchainChild
      have hpair :=
        squareRootCanonicalRoughResponseCenteredReciprocalSummand_add_mul_freshPrime
          hR hc hq hfresh
      simp only [squareRootCanonicalRoughCubeReciprocalPotential,
        squareRootCanonicalRoughCubeReciprocalDefect,
        squareRootCanonicalRoughCubeEulerFactor_cons]
      rw [hbase, hchild]
      linear_combination squareRootCanonicalRoughCubeEulerFactor L * hpair

/-- The accumulated defect never exceeds the sum of the individual step defects:
no Euler factor collected along the way can amplify an earlier defect. -/
theorem norm_squareRootCanonicalRoughCubeReciprocalDefect_le_budget
    (R : ℕ) (L : List ℕ) :
    ∀ c : ℕ, (∀ q ∈ L, 2 ≤ q) →
      ‖squareRootCanonicalRoughCubeReciprocalDefect R L c‖ ≤
        squareRootCanonicalRoughCubeReciprocalDefectBudget R L c := by
  induction L with
  | nil =>
      intro c _hL
      simp [squareRootCanonicalRoughCubeReciprocalDefect,
        squareRootCanonicalRoughCubeReciprocalDefectBudget]
  | cons q L ih =>
      intro c hL
      have hrest : ∀ r ∈ L, 2 ≤ r := fun r hr => hL r (by simp [hr])
      have hE := norm_squareRootCanonicalRoughCubeEulerFactor_le_one L hrest
      simp only [squareRootCanonicalRoughCubeReciprocalDefect,
        squareRootCanonicalRoughCubeReciprocalDefectBudget]
      refine le_trans (norm_add_le _ _) ?_
      refine add_le_add ?_ (ih (c * q) hrest)
      refine le_trans (norm_add_le _ _) ?_
      refine add_le_add ?_ (ih c hrest)
      rw [norm_mul]
      calc
        ‖squareRootCanonicalRoughCubeEulerFactor L‖ *
              ‖squareRootCanonicalRoughFreshPrimeReciprocalPhysicalDefect R c q‖ ≤
            1 * ‖squareRootCanonicalRoughFreshPrimeReciprocalPhysicalDefect R c q‖ :=
          mul_le_mul_of_nonneg_right hE (norm_nonneg _)
        _ = ‖squareRootCanonicalRoughFreshPrimeReciprocalPhysicalDefect R c q‖ := one_mul _

/-- Every step budget is bounded by its reciprocal window ledger, so the whole
accumulated budget is an explicit finite arithmetic quantity. -/
theorem squareRootCanonicalRoughCubeReciprocalDefectBudget_le_ledgerBudget
    (R : ℕ) (hR : 2 ≤ R) (L : List ℕ) :
    ∀ c : ℕ, 0 < c →
      IsCanonicalFreshPrimeChain (canonicalLargestPrimeFactor c) L →
      squareRootCanonicalRoughCubeReciprocalDefectBudget R L c ≤
        squareRootCanonicalRoughCubeReciprocalLedgerBudget R L c := by
  induction L with
  | nil =>
      intro c _hc _hchain
      simp [squareRootCanonicalRoughCubeReciprocalDefectBudget,
        squareRootCanonicalRoughCubeReciprocalLedgerBudget]
  | cons q L ih =>
      intro c hc hchain
      rcases isCanonicalFreshPrimeChain_cons.1 hchain with ⟨hq, hfresh, hrest⟩
      have hcq : 0 < c * q := Nat.mul_pos hc hq.pos
      have hlpf : canonicalLargestPrimeFactor (c * q) = q :=
        canonicalLargestPrimeFactor_mul_prime_eq_of_rough hc hq hfresh
      have hchainBase : IsCanonicalFreshPrimeChain (canonicalLargestPrimeFactor c) L :=
        isCanonicalFreshPrimeChain_of_le (le_of_lt hfresh) hrest
      have hchainChild :
          IsCanonicalFreshPrimeChain (canonicalLargestPrimeFactor (c * q)) L := by
        rw [hlpf]
        exact hrest
      simp only [squareRootCanonicalRoughCubeReciprocalDefectBudget,
        squareRootCanonicalRoughCubeReciprocalLedgerBudget]
      refine add_le_add (add_le_add ?_ (ih c hc hchainBase)) (ih (c * q) hcq hchainChild)
      exact norm_squareRootCanonicalRoughFreshPrimeReciprocalPhysicalDefect_le_ledgerWindow
        hR hc hq hfresh

/-- **Many-prime contraction with controlled defect.**  The compressed cube is
bounded by the real Euler product of the chain times the base reciprocal
potential, plus the accumulated defect budget. -/
theorem norm_squareRootCanonicalRoughCubeReciprocalPotential_le
    (R : ℕ) (hR : 2 ≤ R) (L : List ℕ) (c : ℕ) (hc : 0 < c)
    (hchain : IsCanonicalFreshPrimeChain (canonicalLargestPrimeFactor c) L) :
    ‖squareRootCanonicalRoughCubeReciprocalPotential R L c‖ ≤
      squareRootCanonicalRoughCubeEulerFactorReal L *
          ‖squareRootCanonicalRoughResponseCenteredReciprocalSummand R c‖ +
        squareRootCanonicalRoughCubeReciprocalDefectBudget R L c := by
  have h2 := two_le_of_isCanonicalFreshPrimeChain L _ hchain
  rw [squareRootCanonicalRoughCubeReciprocalPotential_eq_eulerFactor_mul_add_defect
    R hR L c hc hchain]
  refine le_trans (norm_add_le _ _) ?_
  refine add_le_add ?_
    (norm_squareRootCanonicalRoughCubeReciprocalDefect_le_budget R L c h2)
  refine le_of_eq ?_
  rw [norm_mul, norm_squareRootCanonicalRoughCubeEulerFactor_eq_real L h2]

/-- **Quantitative contraction theorem.**  Along any ascending chain of fresh
primes the compressed reciprocal covariance profile decays at the Mertens
exponential rate of the chain, and everything lost to the three physical
boundary channels is bounded by an explicit finite reciprocal-window ledger.

This is the quantitative statement the exact Euler identities were missing: the
contraction factor is genuinely smaller than one and shrinks with the chain,
while the defect ledger is a concrete arithmetic sum rather than an unbounded
signed remainder. -/
theorem norm_squareRootCanonicalRoughCubeReciprocalPotential_le_exp_add_ledger
    (R : ℕ) (hR : 2 ≤ R) (L : List ℕ) (c : ℕ) (hc : 0 < c)
    (hchain : IsCanonicalFreshPrimeChain (canonicalLargestPrimeFactor c) L) :
    ‖squareRootCanonicalRoughCubeReciprocalPotential R L c‖ ≤
      Real.exp (-squareRootCanonicalRoughCubeReciprocalPrimeSum L) *
          ‖squareRootCanonicalRoughResponseCenteredReciprocalSummand R c‖ +
        squareRootCanonicalRoughCubeReciprocalLedgerBudget R L c := by
  have h2 := two_le_of_isCanonicalFreshPrimeChain L _ hchain
  refine le_trans
    (norm_squareRootCanonicalRoughCubeReciprocalPotential_le R hR L c hc hchain) ?_
  refine add_le_add ?_
    (squareRootCanonicalRoughCubeReciprocalDefectBudget_le_ledgerBudget R hR L c hc hchain)
  exact mul_le_mul_of_nonneg_right
    (squareRootCanonicalRoughCubeEulerFactorReal_le_exp_neg L h2) (norm_nonneg _)

/-- The cube of a two-element chain is exactly the Boolean square of
`CanonicalRoughReciprocalCompression`, so the two-prime accumulation theorem
there is the length-two instance of the chain contraction above. -/
theorem squareRootCanonicalRoughCubeReciprocalPotential_twoPrime (R c p q : ℕ) :
    squareRootCanonicalRoughCubeReciprocalPotential R [p, q] c =
      (squareRootCanonicalRoughResponseCenteredReciprocalSummand R c +
          squareRootCanonicalRoughResponseCenteredReciprocalSummand R (c * q)) +
        (squareRootCanonicalRoughResponseCenteredReciprocalSummand R (c * p) +
          squareRootCanonicalRoughResponseCenteredReciprocalSummand R (c * p * q)) := by
  simp only [squareRootCanonicalRoughCubeReciprocalPotential]

end RHLean.Proof
