import Mathlib
import RHLean.Proof.BirthMovingAbsorption
import RHLean.Proof.HeightShellReconstruction

/-!
# Lifetime interval overlap kernel

A canonical source atom `(j,m)` is active at stage `t` when it has already been
born (`j ≤ t`) and its fixed doubled `2ab` height remains above the current
moving boundary. This module proves that the translated-window conjugate
energy of any finite weighted atom population is exactly a pair Gram form whose
kernel counts common active times.

The result is entirely finite and algebraic. It introduces no cancellation or
asymptotic assumption.
-/

noncomputable section

open scoped BigOperators ComplexConjugate

namespace RHLean.Proof

/-- A source atom is alive at stage `t` precisely between its birth block and
its moving-boundary absorption time. -/
def IsLifetimeActive (Λ : ℝ) (p : CanonicalSourceAtom) (t : ℕ) : Prop :=
  p.1 ≤ t ∧ IsMovingCanonicalHigh Λ t p.2

instance instDecidableIsLifetimeActive
    (Λ : ℝ) (p : CanonicalSourceAtom) (t : ℕ) :
    Decidable (IsLifetimeActive Λ p t) := by
  unfold IsLifetimeActive IsMovingCanonicalHigh
  infer_instance

/-- Weighted amplitude of the atoms alive at stage `t`. -/
def lifetimeAmplitude
    (U : Finset CanonicalSourceAtom)
    (w : CanonicalSourceAtom → ℂ) (Λ : ℝ) (t : ℕ) : ℂ :=
  ∑ p ∈ U, if IsLifetimeActive Λ p t then w p else 0

/-- Conjugate energy of the lifetime amplitude on `[N,N+H)`. -/
def lifetimeWindowEnergy
    (U : Finset CanonicalSourceAtom)
    (w : CanonicalSourceAtom → ℂ) (Λ : ℝ) (N H : ℕ) : ℂ :=
  ∑ h ∈ Finset.range H,
    conj (lifetimeAmplitude U w Λ (N + h)) *
      lifetimeAmplitude U w Λ (N + h)

/-- Ordered-pair expansion before the time variable is interchanged with the
pair variables. -/
def lifetimeWindowPairEnergy
    (U : Finset CanonicalSourceAtom)
    (w : CanonicalSourceAtom → ℂ) (Λ : ℝ) (N H : ℕ) : ℂ :=
  ∑ h ∈ Finset.range H,
    ∑ p ∈ U, ∑ q ∈ U,
      if IsLifetimeActive Λ p (N + h) ∧ IsLifetimeActive Λ q (N + h) then
        conj (w p) * w q
      else 0

/-- The overlap kernel counts, as a complex scalar, how many stages in the
observation window contain both atoms. -/
def lifetimeOverlapKernel
    (Λ : ℝ) (N H : ℕ)
    (p q : CanonicalSourceAtom) : ℂ :=
  ∑ h ∈ Finset.range H,
    if IsLifetimeActive Λ p (N + h) ∧ IsLifetimeActive Λ q (N + h)
    then 1 else 0

/-- Pair Gram form generated by the lifetime-overlap kernel. -/
def lifetimeOverlapGram
    (U : Finset CanonicalSourceAtom)
    (w : CanonicalSourceAtom → ℂ) (Λ : ℝ) (N H : ℕ) : ℂ :=
  ∑ p ∈ U, ∑ q ∈ U,
    conj (w p) * w q * lifetimeOverlapKernel Λ N H p q

/-- At one stage, the conjugate square of the active amplitude is exactly its
ordered-pair expansion. -/
theorem lifetimeAmplitude_conj_mul_eq_pairEnergy
    (U : Finset CanonicalSourceAtom)
    (w : CanonicalSourceAtom → ℂ) (Λ : ℝ) (t : ℕ) :
    conj (lifetimeAmplitude U w Λ t) * lifetimeAmplitude U w Λ t =
      ∑ p ∈ U, ∑ q ∈ U,
        if IsLifetimeActive Λ p t ∧ IsLifetimeActive Λ q t then
          conj (w p) * w q
        else 0 := by
  classical
  unfold lifetimeAmplitude
  simp_rw [map_sum]
  rw [Finset.sum_mul]
  apply Finset.sum_congr rfl
  intro p hpU
  rw [Finset.mul_sum]
  apply Finset.sum_congr rfl
  intro q hqU
  by_cases hp : IsLifetimeActive Λ p t <;>
    by_cases hq : IsLifetimeActive Λ q t <;> simp [hp, hq]

/-- Exact translated-window expansion into time-indexed pair energies. -/
theorem lifetimeWindowEnergy_eq_pairEnergy
    (U : Finset CanonicalSourceAtom)
    (w : CanonicalSourceAtom → ℂ) (Λ : ℝ) (N H : ℕ) :
    lifetimeWindowEnergy U w Λ N H =
      lifetimeWindowPairEnergy U w Λ N H := by
  classical
  unfold lifetimeWindowEnergy lifetimeWindowPairEnergy
  apply Finset.sum_congr rfl
  intro h hh
  exact lifetimeAmplitude_conj_mul_eq_pairEnergy U w Λ (N + h)

/-- Interchanging the finite time and pair sums produces the exact overlap
kernel Gram form. -/
theorem lifetimeWindowPairEnergy_eq_overlapGram
    (U : Finset CanonicalSourceAtom)
    (w : CanonicalSourceAtom → ℂ) (Λ : ℝ) (N H : ℕ) :
    lifetimeWindowPairEnergy U w Λ N H =
      lifetimeOverlapGram U w Λ N H := by
  classical
  unfold lifetimeWindowPairEnergy lifetimeOverlapGram lifetimeOverlapKernel
  rw [Finset.sum_comm]
  apply Finset.sum_congr rfl
  intro p hp
  rw [Finset.sum_comm]
  apply Finset.sum_congr rfl
  intro q hq
  rw [Finset.mul_sum]
  apply Finset.sum_congr rfl
  intro h hh
  by_cases hactive : IsLifetimeActive Λ p (N + h) ∧
      IsLifetimeActive Λ q (N + h)
  · simp [hactive]
  · simp [hactive]

/-- The exact lifetime-overlap identity. -/
theorem lifetimeWindowEnergy_eq_overlapGram
    (U : Finset CanonicalSourceAtom)
    (w : CanonicalSourceAtom → ℂ) (Λ : ℝ) (N H : ℕ) :
    lifetimeWindowEnergy U w Λ N H =
      lifetimeOverlapGram U w Λ N H := by
  rw [lifetimeWindowEnergy_eq_pairEnergy]
  exact lifetimeWindowPairEnergy_eq_overlapGram U w Λ N H

/-- The overlap kernel is symmetric. -/
theorem lifetimeOverlapKernel_symm
    (Λ : ℝ) (N H : ℕ) (p q : CanonicalSourceAtom) :
    lifetimeOverlapKernel Λ N H p q =
      lifetimeOverlapKernel Λ N H q p := by
  classical
  unfold lifetimeOverlapKernel
  apply Finset.sum_congr rfl
  intro h hh
  by_cases hp : IsLifetimeActive Λ p (N + h) <;>
    by_cases hq : IsLifetimeActive Λ q (N + h) <;> simp [hp, hq]

/-- The diagonal kernel is the number of active stages for that atom. -/
theorem lifetimeOverlapKernel_self
    (Λ : ℝ) (N H : ℕ) (p : CanonicalSourceAtom) :
    lifetimeOverlapKernel Λ N H p p =
      ∑ h ∈ Finset.range H,
        if IsLifetimeActive Λ p (N + h) then 1 else 0 := by
  classical
  unfold lifetimeOverlapKernel
  apply Finset.sum_congr rfl
  intro h hh
  by_cases hp : IsLifetimeActive Λ p (N + h) <;> simp [hp]

/-- Canonical birth-high universe through a terminal block. -/
def canonicalLifetimeUniverse (Λ : ℝ) (T : ℕ) : Finset CanonicalSourceAtom :=
  birthCanonicalHighAtomSet Λ T

/-- Canonical Möbius-weighted lifetime amplitude. -/
def canonicalLifetimeAmplitude (Λ : ℝ) (T t : ℕ) : ℂ :=
  lifetimeAmplitude (canonicalLifetimeUniverse Λ T)
    canonicalHighAtomWeight Λ t

/-- Canonical lifetime local energy. -/
def canonicalLifetimeWindowEnergy (Λ : ℝ) (T N H : ℕ) : ℂ :=
  lifetimeWindowEnergy (canonicalLifetimeUniverse Λ T)
    canonicalHighAtomWeight Λ N H

/-- Canonical specialization of the exact overlap identity. -/
theorem canonicalLifetimeWindowEnergy_eq_overlapGram
    (Λ : ℝ) (T N H : ℕ) :
    canonicalLifetimeWindowEnergy Λ T N H =
      lifetimeOverlapGram (canonicalLifetimeUniverse Λ T)
        canonicalHighAtomWeight Λ N H := by
  exact lifetimeWindowEnergy_eq_overlapGram
    (canonicalLifetimeUniverse Λ T) canonicalHighAtomWeight Λ N H

/-- A zero-length observation window has zero energy and zero Gram form. -/
example (U : Finset CanonicalSourceAtom)
    (w : CanonicalSourceAtom → ℂ) (Λ : ℝ) (N : ℕ) :
    lifetimeWindowEnergy U w Λ N 0 = 0 ∧
      lifetimeOverlapGram U w Λ N 0 = 0 := by
  simp [lifetimeWindowEnergy, lifetimeOverlapGram, lifetimeOverlapKernel]

/-- The one-stage overlap identity is executable without any analytic premise. -/
example (U : Finset CanonicalSourceAtom)
    (w : CanonicalSourceAtom → ℂ) (Λ : ℝ) (N : ℕ) :
    lifetimeWindowEnergy U w Λ N 1 =
      lifetimeOverlapGram U w Λ N 1 :=
  lifetimeWindowEnergy_eq_overlapGram U w Λ N 1

end RHLean.Proof
