import Mathlib
import RHLean.Arithmetic.PrimeFaceMoebius
import RHLean.Proof.LowWheelHighPrimeSurvivor

/-!
# Boolean-cube expansion of high-prime survivor frequencies

The high-prime multiplicity from `LowWheelHighPrimeSurvivor` is generated by a
finite low-prime divisibility wheel.  This module expands that survivor
indicator over the Boolean cube of low-prime faces, before any magnitude is
taken.

For a low-prime face `t`, `primeFaceProduct t` is the squarefree product of its
coordinates and `booleanCubeSign t` is its Möbius sign.  The survivor count on
`(R,B]` is therefore an exact alternating sum of the counts of multiples of
these face products.
-/

noncomputable section

open scoped ArithmeticFunction.Moebius BigOperators

namespace RHLean.Proof

open RHLean.Arithmetic

attribute [local instance] Classical.propDecidable

/-- Low-prime coordinates that actually divide one physical integer. -/
def lowWheelDividingPrimeSet (R q : ℕ) : Finset ℕ :=
  (primesUpTo R).filter fun p => p ∣ q

private theorem prime_finset_prod_dvd_of_all_dvd
    {t : Finset ℕ} {q : ℕ}
    (hprime : ∀ p ∈ t, p.Prime)
    (hall : ∀ p ∈ t, p ∣ q) :
    t.prod id ∣ q := by
  classical
  induction t using Finset.induction_on with
  | empty => simp
  | @insert p t hp ih =>
      have hpPrime : p.Prime := hprime p (Finset.mem_insert_self p t)
      have htPrime : ∀ r ∈ t, r.Prime := by
        intro r hr
        exact hprime r (Finset.mem_insert_of_mem hr)
      have hpq : p ∣ q := hall p (Finset.mem_insert_self p t)
      have htq : ∀ r ∈ t, r ∣ q := by
        intro r hr
        exact hall r (Finset.mem_insert_of_mem hr)
      have htprod : t.prod id ∣ q := ih htPrime htq
      have hcop : Nat.Coprime p (t.prod id) := by
        rw [hpPrime.coprime_iff_not_dvd]
        intro hpdiv
        rcases (Prime.dvd_finset_prod_iff hpPrime.prime id).mp hpdiv with
          ⟨r, hrt, hpr⟩
        rcases (htPrime r hrt).eq_one_or_self_of_dvd p hpr with hpOne | hpeq
        · exact hpPrime.ne_one hpOne
        · exact hp (hpeq ▸ hrt)
      have hmul : p * t.prod id ∣ q :=
        hcop.mul_dvd_of_dvd_of_dvd hpq htprod
      simpa [Finset.prod_insert hp] using hmul

/-- A face of distinct prime coordinates divides `q` exactly when each of its
prime coordinates divides `q`. -/
theorem primeFaceProduct_dvd_iff_all_dvd
    {S t : Finset ℕ} {q : ℕ}
    (ht : t ⊆ S) (hprime : ∀ p ∈ S, p.Prime) :
    primeFaceProduct t ∣ q ↔ ∀ p ∈ t, p ∣ q := by
  classical
  change t.prod id ∣ q ↔ ∀ p ∈ t, p ∣ q
  constructor
  · intro hprod p hp
    have hpdiv : p ∣ t.prod id := Finset.dvd_prod_of_mem id hp
    exact hpdiv.trans hprod
  · intro hall
    exact prime_finset_prod_dvd_of_all_dvd
      (fun p hp => hprime p (ht hp)) hall

/-- The face products dividing `q` are exactly the full Boolean cube on the
subset of low primes that divide `q`. -/
theorem lowWheelDivisorFaceSet_eq_powerset
    (R q : ℕ) :
    ((primesUpTo R).powerset.filter fun t => primeFaceProduct t ∣ q) =
      (lowWheelDividingPrimeSet R q).powerset := by
  classical
  ext t
  constructor
  · intro ht
    rcases Finset.mem_filter.mp ht with ⟨htPow, hprod⟩
    have htSub : t ⊆ primesUpTo R := Finset.mem_powerset.mp htPow
    have hall :=
      (primeFaceProduct_dvd_iff_all_dvd htSub
        (fun p hp => prime_of_mem_primesUpTo hp)).1 hprod
    apply Finset.mem_powerset.mpr
    intro p hp
    exact Finset.mem_filter.mpr ⟨htSub hp, hall p hp⟩
  · intro ht
    have htDiv : t ⊆ lowWheelDividingPrimeSet R q :=
      Finset.mem_powerset.mp ht
    have htSub : t ⊆ primesUpTo R := by
      intro p hp
      exact (Finset.mem_filter.mp (htDiv hp)).1
    have hall : ∀ p ∈ t, p ∣ q := by
      intro p hp
      exact (Finset.mem_filter.mp (htDiv hp)).2
    apply Finset.mem_filter.mpr
    exact ⟨Finset.mem_powerset.mpr htSub,
      (primeFaceProduct_dvd_iff_all_dvd htSub
        (fun p hp => prime_of_mem_primesUpTo hp)).2 hall⟩

/-- No low prime divides `q` exactly when the dividing-prime set is empty. -/
theorem lowWheelDividingPrimeSet_eq_empty_iff
    (R q : ℕ) :
    lowWheelDividingPrimeSet R q = ∅ ↔ lowWheelHighSurvivor R q := by
  constructor
  · intro hempty p hp hpq
    have : p ∈ lowWheelDividingPrimeSet R q :=
      Finset.mem_filter.mpr ⟨hp, hpq⟩
    rw [hempty] at this
    simp at this
  · intro hsurv
    apply Finset.eq_empty_iff_forall_notMem.mpr
    intro p hp
    rcases Finset.mem_filter.mp hp with ⟨hpR, hpq⟩
    exact hsurv p hpR hpq

/-- Alternating low-prime-face divisor indicator at one integer. -/
def lowWheelDivisorFaceSum (R q : ℕ) : ℤ :=
  ∑ t ∈ (primesUpTo R).powerset,
    if primeFaceProduct t ∣ q then booleanCubeSign t else 0

/-- **Pointwise inclusion-exclusion.**  The alternating face divisor sum is the
exact indicator that `q` survives every low-prime coordinate. -/
theorem lowWheelDivisorFaceSum_eq_survivorIndicator
    (R q : ℕ) :
    lowWheelDivisorFaceSum R q =
      if lowWheelHighSurvivor R q then 1 else 0 := by
  classical
  unfold lowWheelDivisorFaceSum
  rw [← Finset.sum_filter, lowWheelDivisorFaceSet_eq_powerset]
  change booleanCubeAlternatingSum (lowWheelDividingPrimeSet R q) = _
  by_cases hsurv : lowWheelHighSurvivor R q
  · have hempty : lowWheelDividingPrimeSet R q = ∅ :=
      (lowWheelDividingPrimeSet_eq_empty_iff R q).2 hsurv
    rw [hempty, booleanCubeAlternatingSum_empty]
    simp [hsurv]
  · have hne : (lowWheelDividingPrimeSet R q).Nonempty := by
      unfold lowWheelHighSurvivor at hsurv
      push_neg at hsurv
      rcases hsurv with ⟨p, hpR, hpq⟩
      exact ⟨p, Finset.mem_filter.mpr ⟨hpR, hpq⟩⟩
    rw [booleanCubeAlternatingSum_eq_zero hne]
    simp [hsurv]

/-- Divisibility population of one low-prime face inside `(R,B]`. -/
def lowWheelFaceMultipleSet (R B : ℕ) (t : Finset ℕ) : Finset ℕ :=
  (Finset.Ioc R B).filter fun q => primeFaceProduct t ∣ q

/-- The integer survivor count is the sum of the pointwise low-wheel
inclusion-exclusion indicators. -/
theorem lowWheelHighSurvivorSet_card_eq_sum_faceIndicators
    (R B : ℕ) :
    ((lowWheelHighSurvivorSet R B).card : ℤ) =
      ∑ q ∈ Finset.Ioc R B, lowWheelDivisorFaceSum R q := by
  classical
  unfold lowWheelHighSurvivorSet
  calc
    (((Finset.Ioc R B).filter (lowWheelHighSurvivor R)).card : ℤ) =
        ∑ q ∈ (Finset.Ioc R B).filter (lowWheelHighSurvivor R), (1 : ℤ) := by
          simp
    _ = ∑ q ∈ Finset.Ioc R B,
          if lowWheelHighSurvivor R q then (1 : ℤ) else 0 := by
          rw [Finset.sum_filter]
    _ = ∑ q ∈ Finset.Ioc R B, lowWheelDivisorFaceSum R q := by
          apply Finset.sum_congr rfl
          intro q _hq
          rw [lowWheelDivisorFaceSum_eq_survivorIndicator]

/-- **Finite low-wheel frequency expansion.**  The high-survivor multiplicity
is an alternating sum over low-prime faces, with each face weighted only by the
number of physical integers in `(R,B]` divisible by its squarefree product. -/
theorem lowWheelHighSurvivorSet_card_eq_faceMultipleCounts
    (R B : ℕ) :
    ((lowWheelHighSurvivorSet R B).card : ℤ) =
      ∑ t ∈ (primesUpTo R).powerset,
        booleanCubeSign t * (lowWheelFaceMultipleSet R B t).card := by
  classical
  rw [lowWheelHighSurvivorSet_card_eq_sum_faceIndicators]
  unfold lowWheelDivisorFaceSum lowWheelFaceMultipleSet
  calc
    (∑ q ∈ Finset.Ioc R B,
        ∑ t ∈ (primesUpTo R).powerset,
          if primeFaceProduct t ∣ q then booleanCubeSign t else 0) =
      ∑ t ∈ (primesUpTo R).powerset,
        ∑ q ∈ Finset.Ioc R B,
          if primeFaceProduct t ∣ q then booleanCubeSign t else 0 := by
            rw [Finset.sum_comm]
    _ = ∑ t ∈ (primesUpTo R).powerset,
        booleanCubeSign t *
          (((Finset.Ioc R B).filter fun q => primeFaceProduct t ∣ q).card : ℤ) := by
      apply Finset.sum_congr rfl
      intro t _ht
      rw [← Finset.sum_filter]
      simp [mul_comm]

end RHLean.Proof
