import Mathlib
import RHLean.Proof.LowWheelTransportTripleCarrier

/-!
# Mixed second finite difference on the two low-wheel sign coordinates

After the high-prime multiplicity has been expanded into the low wheel, the
transport carrier has two independent signed coordinates: the squarefree
cofactor face and the survivor-sieve face.  Toggling one prime in either copy
produces a four-corner Boolean cell.

At the indicator level, write

* `L_R(q) = 1[R < q]` for the lower/root boundary;
* `U_X(n) = 1[n <= X]` for the square-endpoint boundary;
* `H(R,X,q,n) = L_R(q) U_X(n)`.

For one prime `p`, the four signed corners are

`H(q,n) - H(q,pn) - H(pq,pn) + H(pq,p^2 n)`.

The main theorem splits this *exactly* into

* a second multiplicative finite difference at the square endpoint, and
* a mixed boundary term where the lower cutoff changes when `q` is multiplied
  by `p`.

For `p = 2` the entire cell collapses onto the two factor-four endpoint shells.
The outer shell survives only above the root cutoff, while the inner shell sees
the enlarged dyadic cutoff `R < 2q`.

No norm or asymptotic estimate appears.
-/

noncomputable section

namespace RHLean.Proof

/-- Lower-bound indicator for the transport quotient. -/
def lowWheelRootHighIndicator (R q : ℕ) : ℤ :=
  if R < q then 1 else 0

/-- Upper square-endpoint indicator. -/
def lowWheelEndpointIndicator (X n : ℕ) : ℤ :=
  if n ≤ X then 1 else 0

/-- Product indicator of one prime-count-free transport state. -/
def lowWheelTransportIndicator (R X q n : ℕ) : ℤ :=
  lowWheelRootHighIndicator R q * lowWheelEndpointIndicator X n

/-- One four-corner mixed Boolean cell obtained by toggling `p` in the
cofactor face, the sieve face, or both. -/
def lowWheelMixedPrimeCell (p R X q n : ℕ) : ℤ :=
  lowWheelTransportIndicator R X q n -
    lowWheelTransportIndicator R X q (p * n) -
    lowWheelTransportIndicator R X (p * q) (p * n) +
    lowWheelTransportIndicator R X (p * q) (p * p * n)

/-- Multiplicative second finite difference of the endpoint indicator. -/
def lowWheelEndpointSecondDifference (p X n : ℕ) : ℤ :=
  lowWheelEndpointIndicator X n -
    2 * lowWheelEndpointIndicator X (p * n) +
    lowWheelEndpointIndicator X (p * p * n)

/-- Lower-cutoff first difference generated by multiplying the quotient base by
one prime. -/
def lowWheelRootCrossingDifference (p R q : ℕ) : ℤ :=
  lowWheelRootHighIndicator R q - lowWheelRootHighIndicator R (p * q)

/-- Endpoint first difference on the once-dilated state. -/
def lowWheelEndpointCrossingDifference (p X n : ℕ) : ℤ :=
  lowWheelEndpointIndicator X (p * n) -
    lowWheelEndpointIndicator X (p * p * n)

/-- **Exact mixed finite-difference decomposition.**  The two-copy low-wheel
four-corner cell is a bulk second difference plus one lower-cutoff crossing
term.  This is a ring identity after the indicators are named. -/
theorem lowWheelMixedPrimeCell_eq_bulk_add_crossing
    (p R X q n : ℕ) :
    lowWheelMixedPrimeCell p R X q n =
      lowWheelRootHighIndicator R q *
          lowWheelEndpointSecondDifference p X n +
        lowWheelRootCrossingDifference p R q *
          lowWheelEndpointCrossingDifference p X n := by
  unfold lowWheelMixedPrimeCell lowWheelTransportIndicator
    lowWheelEndpointSecondDifference lowWheelRootCrossingDifference
    lowWheelEndpointCrossingDifference
  ring

/-- For prime two, the lower-cutoff difference is exactly the dyadic crossing
band `q <= R < 2q`, with sign `-1`. -/
theorem lowWheelRootCrossingDifference_two
    (R q : ℕ) :
    lowWheelRootCrossingDifference 2 R q =
      if q ≤ R ∧ R < 2 * q then -1 else 0 := by
  unfold lowWheelRootCrossingDifference lowWheelRootHighIndicator
  by_cases hq : R < q
  · have h2q : R < 2 * q := by omega
    simp [hq, h2q]
  · have hqR : q ≤ R := Nat.le_of_not_gt hq
    by_cases h2q : R < 2 * q
    · simp [hq, hqR, h2q]
    · simp [hq, hqR, h2q]

/-- For prime two, the endpoint first difference is exactly the factor-four
annulus `2n <= X < 4n`. -/
theorem lowWheelEndpointCrossingDifference_two
    (X n : ℕ) :
    lowWheelEndpointCrossingDifference 2 X n =
      if 2 * n ≤ X ∧ X < 4 * n then 1 else 0 := by
  unfold lowWheelEndpointCrossingDifference lowWheelEndpointIndicator
  split_ifs <;> omega

/-- The prime-two endpoint *second* difference vanishes away from two adjacent
factor-four shells.  It is `+1` on the outer half-shell and `-1` on the inner
quarter-to-half shell. -/
theorem lowWheelEndpointSecondDifference_two
    (X n : ℕ) :
    lowWheelEndpointSecondDifference 2 X n =
      (if n ≤ X ∧ X < 2 * n then 1 else 0) -
        (if 2 * n ≤ X ∧ X < 4 * n then 1 else 0) := by
  unfold lowWheelEndpointSecondDifference lowWheelEndpointIndicator
  split_ifs <;> omega

/-- The entire prime-two mixed boundary is supported on the simultaneous dyadic
root crossing and factor-four endpoint annulus. -/
theorem lowWheelPrimeTwoCrossingProduct
    (R X q n : ℕ) :
    lowWheelRootCrossingDifference 2 R q *
        lowWheelEndpointCrossingDifference 2 X n =
      if q ≤ R ∧ R < 2 * q ∧ 2 * n ≤ X ∧ X < 4 * n then -1 else 0 := by
  rw [lowWheelRootCrossingDifference_two,
    lowWheelEndpointCrossingDifference_two]
  by_cases hq : q ≤ R ∧ R < 2 * q <;>
    by_cases hn : 2 * n ≤ X ∧ X < 4 * n <;>
    simp [hq, hn]

/-- **Prime-two four-corner form.**  The exact local transport cell is the
prime-two endpoint second difference plus the explicit factor-four boundary
indicator. -/
theorem lowWheelMixedPrimeCell_two_eq_secondDifference_add_factorFourBoundary
    (R X q n : ℕ) :
    lowWheelMixedPrimeCell 2 R X q n =
      lowWheelRootHighIndicator R q *
          lowWheelEndpointSecondDifference 2 X n +
        (if q ≤ R ∧ R < 2 * q ∧ 2 * n ≤ X ∧ X < 4 * n then -1 else 0) := by
  rw [lowWheelMixedPrimeCell_eq_bulk_add_crossing,
    lowWheelPrimeTwoCrossingProduct]

/-- **Complete factor-four localization.**  Combining the bulk and crossing
pieces removes the artificial split at `q = R`: the outer endpoint shell is
seen for `R < q`, while the inner shell is seen for the enlarged cutoff
`R < 2q`.  The mixed low-wheel prime-two cell is zero everywhere else. -/
theorem lowWheelMixedPrimeCell_two_eq_factorFourShellDifference
    (R X q n : ℕ) :
    lowWheelMixedPrimeCell 2 R X q n =
      (if R < q ∧ n ≤ X ∧ X < 2 * n then 1 else 0) -
        (if R < 2 * q ∧ 2 * n ≤ X ∧ X < 4 * n then 1 else 0) := by
  unfold lowWheelMixedPrimeCell lowWheelTransportIndicator
    lowWheelRootHighIndicator lowWheelEndpointIndicator
  split_ifs <;> omega

end RHLean.Proof
