import Mathlib
import RHLean.Proof.SquareBlockSmoothTransportGram

noncomputable section

open scoped ArithmeticFunction.Moebius BigOperators

namespace RHLean.Proof

/-- The real square endpoint `k^2`, used as an argument of a baseline function. -/
def squareBlockEndpointReal (k : ℕ) : ℝ :=
  ((k ^ 2 : ℕ) : ℝ)

/-- The deterministic transport approximation induced by an arbitrary
complex-valued baseline `F`.

This definition is independent of the actual canonical transport term. It
does not assert that the latter has already been realized as a prime-counting
interval sum. -/
noncomputable def squareBlockBaselineTransportApprox
    (F : ℝ → ℂ) (k : ℕ) : ℂ := by
  classical
  exact
    ∑ c ∈ Finset.Icc 1 k,
      canonicalMoebiusWeight c *
        (F (squareBlockEndpointReal (k + 1) / (c : ℝ)) -
          F (squareBlockEndpointReal k / (c : ℝ)))

/-- The exact residual between the canonical transport increment and the
transport approximation generated by `F`. -/
noncomputable def squareBlockBaselineTransportError
    (F : ℝ → ℂ) (k : ℕ) : ℂ :=
  squareBlockTransportIncrement k -
    squareBlockBaselineTransportApprox F k

/-- Definitional transport recombination. -/
theorem squareBlockTransportIncrement_eq_baselineApprox_add_error
    (F : ℝ → ℂ) (k : ℕ) :
    squareBlockTransportIncrement k =
      squareBlockBaselineTransportApprox F k +
        squareBlockBaselineTransportError F k := by
  unfold squareBlockBaselineTransportError
  ring

/-- The smooth-minus-baseline-transport main increment. -/
noncomputable def squareBlockBaselineMainIncrement
    (F : ℝ → ℂ) (k : ℕ) : ℂ :=
  squareBlockSmoothIncrement k -
    squareBlockBaselineTransportApprox F k

/-- Every exact canonical increment is the baseline main increment minus the
baseline transport error. -/
theorem canonicalTotalIncrement_eq_baselineMain_sub_error
    (F : ℝ → ℂ) (k : ℕ) :
    canonicalTotalIncrement k =
      squareBlockBaselineMainIncrement F k -
        squareBlockBaselineTransportError F k := by
  rw [canonicalTotalIncrement_eq_smooth_sub_transport]
  rw [squareBlockTransportIncrement_eq_baselineApprox_add_error]
  unfold squareBlockBaselineMainIncrement
  ring

/-- Cumulative baseline main contribution from the common-origin blocks
`0,1,...,n`. -/
noncomputable def squareBlockBaselineMainPrefix
    (F : ℝ → ℂ) (n : ℕ) : ℂ :=
  ∑ k ∈ Finset.range (n + 1),
    squareBlockBaselineMainIncrement F k

/-- Cumulative baseline transport error from the same common origin. -/
noncomputable def squareBlockBaselineTransportErrorPrefix
    (F : ℝ → ℂ) (n : ℕ) : ℂ :=
  ∑ k ∈ Finset.range (n + 1),
    squareBlockBaselineTransportError F k

/-- Exact cumulative baseline decomposition. -/
theorem squareBlockSmoothTransportResidual_eq_baselineMain_sub_error
    (F : ℝ → ℂ) (n : ℕ) :
    squareBlockSmoothTransportResidual n =
      squareBlockBaselineMainPrefix F n -
        squareBlockBaselineTransportErrorPrefix F n := by
  rw [← canonicalTotalPrefix_eq_smooth_sub_transport]
  unfold canonicalTotalPrefix squareBlockBaselineMainPrefix
    squareBlockBaselineTransportErrorPrefix
  calc
    (∑ k ∈ Finset.range (n + 1), canonicalTotalIncrement k) =
        ∑ k ∈ Finset.range (n + 1),
          (squareBlockBaselineMainIncrement F k -
            squareBlockBaselineTransportError F k) := by
      apply Finset.sum_congr rfl
      intro k hk
      exact canonicalTotalIncrement_eq_baselineMain_sub_error F k
    _ =
        (∑ k ∈ Finset.range (n + 1),
          squareBlockBaselineMainIncrement F k) -
        ∑ k ∈ Finset.range (n + 1),
          squareBlockBaselineTransportError F k := by
      rw [Finset.sum_sub_distrib]

/-- The concrete square-prefix Mertens value has the same exact baseline
decomposition. -/
theorem squarePrefixMertens_eq_baselineMain_sub_error
    (F : ℝ → ℂ) (n : ℕ) :
    RHLean.Analysis.squarePrefixMertens n =
      squareBlockBaselineMainPrefix F n -
        squareBlockBaselineTransportErrorPrefix F n := by
  rw [← squareBlockSmoothTransportResidual_eq_squarePrefixMertens]
  exact
    squareBlockSmoothTransportResidual_eq_baselineMain_sub_error F n

end RHLean.Proof
