import Mathlib
import RHLean.Proof.SquareRootLowPrimeSignedResponseMatching

/-!
# Child-level displacement diamonds

The signed response-child matching has the same commuting-square structure as
the processed seat carrier.  This file states the mechanism directly on the
arithmetic children, where a missing corner can be passed to the existing
canonical-child and first-failure geometry.

An earlier `q`-matching can make a later `p`-toggle look unstable only by
removing one corner of the `p`-`q` square.  If the translated child survives,
the opposite corner is absent from the carrier.  For a fixed displaced pivot,
different later primes produce different absent arithmetic children.  Thus an
unstable pivot cannot be charged independently for every later prime: every
charge owns a distinct support-boundary child.
-/

noncomputable section

open scoped ArithmeticFunction.Moebius BigOperators

namespace RHLean.Proof

attribute [local instance] Classical.propDecidable

/-- Distinct-prime freshness after one extension. -/
theorem prime_not_dvd_mul_of_distinct_of_not_dvd
    {p q n : ℕ} (hp : p.Prime) (hq : q.Prime) (hpq : p ≠ q)
    (hqn : ¬ q ∣ n) :
    ¬ q ∣ p * n := by
  intro hdiv
  rcases hq.dvd_mul.mp hdiv with hqp | hqn'
  · have hEq : q = p :=
      (Nat.prime_dvd_prime_iff_eq hq hp).mp hqp
    exact hpq hEq.symm
  · exact hqn hqn'

/-- **Lower child displacement forces a missing top corner.** -/
theorem squareRootLowPrimeResponse_lowerDisplacement_forces_top_missing
    {S : Finset ℕ} {p q n : ℕ}
    (hp : p.Prime) (hq : q.Prime) (hpq : p ≠ q)
    (hnLower : n ∈ squareRootLowPrimeResponsePairLower S q)
    (hpnFrontier : p * n ∈ squareRootLowPrimeResponseFrontierStep S q) :
    q * (p * n) ∉ S := by
  intro htop
  have hnData := mem_squareRootLowPrimeResponsePairLower.mp hnLower
  have hpnData := Finset.mem_sdiff.mp hpnFrontier
  have hqFresh : ¬ q ∣ p * n :=
    prime_not_dvd_mul_of_distinct_of_not_dvd hp hq hpq hnData.2.1
  have htranslatedLower :
      p * n ∈ squareRootLowPrimeResponsePairLower S q :=
    mem_squareRootLowPrimeResponsePairLower.mpr
      ⟨hpnData.1, hqFresh, htop⟩
  exact hpnData.2
    (Finset.mem_union.mpr (Or.inl htranslatedLower))

/-- **Upper child displacement forces a missing lower corner.** -/
theorem squareRootLowPrimeResponse_upperDisplacement_forces_bottom_missing
    {S : Finset ℕ} {p q n : ℕ}
    (hp : p.Prime) (hq : q.Prime) (hpq : p ≠ q)
    (hnLower : n ∈ squareRootLowPrimeResponsePairLower S q)
    (hpqnFrontier :
      p * (q * n) ∈ squareRootLowPrimeResponseFrontierStep S q) :
    p * n ∉ S := by
  intro hbottom
  have hnData := mem_squareRootLowPrimeResponsePairLower.mp hnLower
  have htopData := Finset.mem_sdiff.mp hpqnFrontier
  have hqFresh : ¬ q ∣ p * n :=
    prime_not_dvd_mul_of_distinct_of_not_dvd hp hq hpq hnData.2.1
  have htranslatedLower :
      p * n ∈ squareRootLowPrimeResponsePairLower S q :=
    mem_squareRootLowPrimeResponsePairLower.mpr
      ⟨hbottom, hqFresh, by
        have hcomm : q * (p * n) = p * (q * n) := by ac_rfl
        rw [hcomm]
        exact htopData.1⟩
  have htranslatedUpper :
      p * (q * n) ∈ squareRootLowPrimeResponsePairUpper S q := by
    unfold squareRootLowPrimeResponsePairUpper
    apply Finset.mem_image.mpr
    refine ⟨p * n, htranslatedLower, ?_⟩
    ac_rfl
  exact htopData.2
    (Finset.mem_union.mpr (Or.inr htranslatedUpper))

/-- For positive arithmetic children, extension by the prime coordinate is
injective in that coordinate. -/
theorem prime_mul_injective_of_pos
    {n : ℕ} (hn : 0 < n) :
    Function.Injective (fun p : ℕ => p * n) := by
  intro p r hpr
  exact Nat.mul_right_cancel hn hpr

/-- For fixed positive `q` and `n`, the top-corner map `p ↦ q*p*n` is
injective. -/
theorem twoPrimeTopCorner_injective
    {q n : ℕ} (hq : 0 < q) (hn : 0 < n) :
    Function.Injective (fun p : ℕ => q * (p * n)) := by
  intro p r hpr
  have hinner : p * n = r * n := Nat.mul_left_cancel hq hpr
  exact Nat.mul_right_cancel hn hinner

/-- Later primes producing lower displacement at one fixed `q`-pivot. -/
def squareRootLowPrimeResponseLowerDisplacementPrimes
    (S P : Finset ℕ) (q n : ℕ) : Finset ℕ :=
  P.filter fun p =>
    p.Prime ∧ p ≠ q ∧
      p * n ∈ squareRootLowPrimeResponseFrontierStep S q

/-- Missing top corners generated by those displaced later primes. -/
def squareRootLowPrimeResponseLowerDisplacementMissingCorners
    (S P : Finset ℕ) (q n : ℕ) : Finset ℕ :=
  (squareRootLowPrimeResponseLowerDisplacementPrimes S P q n).image
    (fun p => q * (p * n))

/-- Every generated top corner really lies outside the current carrier. -/
theorem squareRootLowPrimeResponseLowerDisplacementMissingCorners_disjoint
    {S P : Finset ℕ} {q n : ℕ} (hq : q.Prime)
    (hnLower : n ∈ squareRootLowPrimeResponsePairLower S q) :
    Disjoint
      (squareRootLowPrimeResponseLowerDisplacementMissingCorners S P q n) S := by
  rw [Finset.disjoint_left]
  intro m hm hmem
  rcases Finset.mem_image.mp hm with ⟨p, hpDisp, rfl⟩
  have hpData := Finset.mem_filter.mp hpDisp
  exact
    (squareRootLowPrimeResponse_lowerDisplacement_forces_top_missing
      hpData.2.1 hq hpData.2.2.1 hnLower hpData.2.2.2) hmem

/-- **No recurrence at a fixed lower pivot.**  Its unstable later-prime
population has exactly as many elements as its distinct missing top corners. -/
theorem card_squareRootLowPrimeResponseLowerDisplacementMissingCorners
    {S P : Finset ℕ} {q n : ℕ} (hq : 0 < q) (hn : 0 < n) :
    (squareRootLowPrimeResponseLowerDisplacementMissingCorners S P q n).card =
      (squareRootLowPrimeResponseLowerDisplacementPrimes S P q n).card := by
  unfold squareRootLowPrimeResponseLowerDisplacementMissingCorners
  exact Finset.card_image_iff.mpr
    (Set.injOn_of_injective (twoPrimeTopCorner_injective hq hn))

/-- Later primes producing upper displacement at one fixed `q`-pivot. -/
def squareRootLowPrimeResponseUpperDisplacementPrimes
    (S P : Finset ℕ) (q n : ℕ) : Finset ℕ :=
  P.filter fun p =>
    p.Prime ∧ p ≠ q ∧
      p * (q * n) ∈ squareRootLowPrimeResponseFrontierStep S q

/-- Missing lower corners generated by upper displacement. -/
def squareRootLowPrimeResponseUpperDisplacementMissingCorners
    (S P : Finset ℕ) (q n : ℕ) : Finset ℕ :=
  (squareRootLowPrimeResponseUpperDisplacementPrimes S P q n).image
    (fun p => p * n)

/-- Every generated lower corner lies outside the current carrier. -/
theorem squareRootLowPrimeResponseUpperDisplacementMissingCorners_disjoint
    {S P : Finset ℕ} {q n : ℕ} (hq : q.Prime)
    (hnLower : n ∈ squareRootLowPrimeResponsePairLower S q) :
    Disjoint
      (squareRootLowPrimeResponseUpperDisplacementMissingCorners S P q n) S := by
  rw [Finset.disjoint_left]
  intro m hm hmem
  rcases Finset.mem_image.mp hm with ⟨p, hpDisp, rfl⟩
  have hpData := Finset.mem_filter.mp hpDisp
  exact
    (squareRootLowPrimeResponse_upperDisplacement_forces_bottom_missing
      hpData.2.1 hq hpData.2.2.1 hnLower hpData.2.2.2) hmem

/-- **No recurrence at a fixed upper pivot.** -/
theorem card_squareRootLowPrimeResponseUpperDisplacementMissingCorners
    {S P : Finset ℕ} {q n : ℕ} (hn : 0 < n) :
    (squareRootLowPrimeResponseUpperDisplacementMissingCorners S P q n).card =
      (squareRootLowPrimeResponseUpperDisplacementPrimes S P q n).card := by
  unfold squareRootLowPrimeResponseUpperDisplacementMissingCorners
  exact Finset.card_image_iff.mpr
    (Set.injOn_of_injective (prime_mul_injective_of_pos hn))

end RHLean.Proof
